version: '3.8'

services:
  backend:
    build: Back-End-TF
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/housekeeper?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 12345678
      PEXEL_KEY: nkLJHJpNOLjVQjk8fGkp0JdwawV0wanoM2zuWeDneEa4Wm4c2OANUGmG
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: housekeeper
      MYSQL_ROOT_PASSWORD: 1234678
      MYSQL_PASSWORD: 12345678
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
